version: "3"
networks:
  moogieapp:

services:
  # Launch the Redis used for syncing messages between copies of the client app
  redis:
    image: redis
    networks:
      - moogieapp
    ports:
      - 6379:6379

  # The actual client application
  client:
    depends_on:
      - redis
    networks:
      - moogieapp
    build: ./src
    environment:
      ENV_NAME: test
      REDIS_ENDPOINT: redis
    ports:
      - 5000:5000
